# Generated by Django 3.2.9 on 2021-12-03 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cursor',
            new_name='Curso',
        ),
    ]
